//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDEvent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addevent
    {
        public string EventName { get; set; }
        public string Region { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }
        public string City { get; set; }
        public string TypeofEvent { get; set; }
        public string NumberOfOfficialsNeeded { get; set; }
    }
}
