//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDEvent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Available
    {
        public int Id { get; set; }
        public string EmailID { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public string RegionsOfAvailability { get; set; }
        public string TypesOfGames { get; set; }
        public string PriorityOfRegions { get; set; }
    
        public virtual User User { get; set; }
    }
}
