//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDEvent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Postal { get; set; }
        public string PhoneNumber { get; set; }
        public string ExperiencinYears { get; set; }
        public string Roles { get; set; }
        public string NonRoles { get; set; }
        public string Justifying { get; set; }
        public string CertificationLevels { get; set; }
        public string MinistryofBackground { get; set; }
        public string AdditionalSkills { get; set; }
        public System.DateTime From { get; set; }
        public System.DateTime To { get; set; }
        public string RegionsOfAvailability { get; set; }
        public string TypesOfGames { get; set; }
        public string PriorityOfRegions { get; set; }
    }
}
